---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev11
spec:
  selector:
    app: iotapp-dev11
  ports:
    - name: dev11-port
      port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev11-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev11
  template:
    metadata:
      labels:
        app: iotapp-dev11
    spec:
      containers:
      - name: iotapp-dev11-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9001 --local_name dev11 --remote_ip iotapp-gwf1 --remote_port 8281 --remote_name gwf1 --send_period 3000"
        ports:
        - containerPort: 9001
