---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev12
spec:
  selector:
    app: iotapp-dev12
  ports:
    - name: dev12-port
      port: 9002
      targetPort: 9002
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev12-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev12
  template:
    metadata:
      labels:
        app: iotapp-dev12
    spec:
      containers:
      - name: iotapp-dev12-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9002 --local_name dev12 --remote_ip iotapp-gwf1 --remote_port 8281 --remote_name gwf1 --send_period 10000"
        ports:
        - containerPort: 9002
