---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev13
spec:
  selector:
    app: iotapp-dev13
  ports:
    - name: dev13-port
      port: 9003
      targetPort: 9003
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev13-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev13
  template:
    metadata:
      labels:
        app: iotapp-dev13
    spec:
      containers:
      - name: iotapp-dev13-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9003 --local_name dev13 --remote_ip iotapp-gwf1 --remote_port 8281 --remote_name gwf1 --send_period 8000"
        ports:
        - containerPort: 9003
