apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gwi-to-decoder
spec:
  hosts:
  - iotapp-server
  http:
  - match:
    - port: 8080
    route:
    - destination:
        host: iotapp-decoder
        port:
          number: 9200
