apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iotapp-controller-role
  namespace: default
rules:
# --- Deployments ---
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

# --- Services ---
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

# --- Istio VirtualService ---
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
