apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iotapp-controller-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: iotapp-controller-sa
  namespace: default
roleRef:
  kind: Role
  name: iotapp-controller-role
  apiGroup: rbac.authorization.k8s.io
