# Service ClusterIP for Gateway
apiVersion: v1
kind: Service
metadata:
  name: device-clusterip
spec:
  selector:
    app: iotapp-device
  ports:
  - protocol: TCP
    name: local-port    
    port: 9001
    targetPort: 9001
  - protocol: TCP
    name: remote-port
    port: 8282
    targetPort: 8282
  type: ClusterIP
