apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-device-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-device
  template:
    metadata:
      labels:
        app: iotapp-device
    spec:
      containers:
      - name: iotapp-device-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9001 --local_name dev1 --remote_ip iotapp-gwf1 --remote_port 8282 --remote_name gwf1 --send_period 3000"
        ports:
        - containerPort: 9001
