---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev31
spec:
  selector:
    app: iotapp-dev31
  ports:
    - name: dev31-port
      port: 9007
      targetPort: 9007
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev31-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev31
  template:
    metadata:
      labels:
        app: iotapp-dev31
    spec:
      containers:
      - name: iotapp-dev31-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9007 --local_name dev31 --remote_ip iotapp-gwf3 --remote_port 8283 --remote_name gwf3 --send_period 3000"
        ports:
        - containerPort: 9007
