---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev33
spec:
  selector:
    app: iotapp-dev33
  ports:
    - name: dev33-port
      port: 9009
      targetPort: 9009
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev33-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev33
  template:
    metadata:
      labels:
        app: iotapp-dev33
    spec:
      containers:
      - name: iotapp-dev33-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9009 --local_name dev33 --remote_ip iotapp-gwf3 --remote_port 8283 --remote_name gwf3 --send_period 3000"
        ports:
        - containerPort: 9009
