---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-gwf3
spec:
  selector:
    app: iotapp-gwf3
  ports:
    - name: gwf3-port
      port: 8283
      targetPort: 8283
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-gwf3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-gwf3
  template:
    metadata:
      labels:
        app: iotapp-gwf3
    spec:
      containers:
      - name: iotapp-gwf3-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "gateway/gateway.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 8283 --local_name gwf3 --remote_ip iotapp-gwi-z3 --remote_port 8184 --remote_name gwi"
        ports:
        - containerPort: 8283
