apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-decoder
  template:
    metadata:
      labels:
        app: iotapp-decoder
    spec:
      serviceAccountName: iotapp-controller-sa
      containers:
      - name: decoder
        image: iotapp-controller:latest
        imagePullPolicy: IfNotPresent

        command: ["node", "runner.js"]

        env:
        - name: SERVICE
          value: "decoder/decoder.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9200 --local_name decoder --remote_ip iotapp-server --remote_port 8181 --remote_name iotapp-server"

        ports:
        - containerPort: 9200
