apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-server
  template:
    metadata:
      labels:
        app: iotapp-server
    spec:
      containers:
      - name: iotapp-server-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "server/server.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 8080 --local_name srv"
        ports:
        - containerPort: 8080