# Deployment Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-server-deployment
spec:
  selector:
    matchLabels:
      app: iotapp-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: iotapp-server-deployment
    spec:
      containers:
      - name: iotapp-server-container
        image: 10.0.0.89:5000/iotapp-node-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE
          value: "server/server.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 8080 --local_name srv"
        ports:
        - containerPort: 8080
