---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-shouting-device1
spec:
  selector:
    app: iotapp-shouting-device1
  ports:
    - name: local-port
      port: 9010
      targetPort: 9010
      protocol: TCP
---
# Deployment Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-shouting-device1
spec:
  selector:
    matchLabels:
      app: iotapp-shouting-device1
  replicas: 1
  template:
    metadata:
      labels:
        app: iotapp-shouting-device1
    spec:
      containers:
      - name: iotapp-shouting-device1-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9010 --local_name shtdev1 --remote_ip iotapp-gwf1 --remote_port 8281 --remote_name gwf1 --send_period 1"
        ports:
        - containerPort: 9010
