apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: encoder-traffic-shift
spec:
  hosts:
  - iotapp-gwi
  http:
  - match:
    - port: 8181
    route:
    - destination:
        host: iotapp-encoder
        port:
          number: 9100
