---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-gwi-forward
spec:
  selector:
    app: iotapp-gwi   # SAME pods
  ports:
  - name: http
    port: 8181
    targetPort: 8181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-encoder
  template:
    metadata:
      labels:
        app: iotapp-encoder
    spec:
      serviceAccountName: iotapp-controller-sa
      containers:
      - name: encoder
        image: iotapp-controller:latest
        imagePullPolicy: IfNotPresent

        
        command: ["node", "runner.js"]

        env:
        - name: SERVICE
          value: "encoder/encoder.js"
        - name: ARGS
          value: >
            --local_ip 0.0.0.0
            --local_port 9100
            --local_name encoder
            --remote_ip iotapp-gwi-forward
            --remote_port 8181
            --remote_name gwi-forward
            --buffer_size 2

        ports:
        - containerPort: 9100
