---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev23
spec:
  selector:
    app: iotapp-dev23
  ports:
    - name: dev23-port
      port: 9006
      targetPort: 9006
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev23-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev23
  template:
    metadata:
      labels:
        app: iotapp-dev23
    spec:
      containers:
      - name: iotapp-dev23-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9006 --local_name dev23 --remote_ip iotapp-gwf2 --remote_port 8282 --remote_name gwf2 --send_period 5000"
        ports:
        - containerPort: 9006
