---
apiVersion: v1
kind: Service
metadata:
  name: iotapp-dev21
spec:
  selector:
    app: iotapp-dev21
  ports:
    - name: dev21-port
      port: 9004
      targetPort: 9004
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-dev21-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-dev21
  template:
    metadata:
      labels:
        app: iotapp-dev21
    spec:
      containers:
      - name: iotapp-dev21-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "device/device.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 9004 --local_name dev21 --remote_ip iotapp-gwf2 --remote_port 8282 --remote_name gwf2 --send_period 9000"
        ports:
        - containerPort: 9004
