apiVersion: v1
kind: Service
metadata:
  name: iotapp-gwf1
spec:
  selector:
    app: iotapp-gwf1
  ports:
    - name: local-port
      port: 8282
      targetPort: 8282
      protocol: TCP
    - name: remote-port
      port: 8181
      targetPort: 8181
      protocol: TCP
