# Service ClusterIP for Gateway
apiVersion: v1
kind: Service
metadata:
  name: gwi-clusterip
spec:
  selector:
    app: iotapp-gwi
  ports:
  - protocol: TCP
    name: local-port   
    port: 8181
    targetPort: 8181
  - protocol: TCP
    name: remote-port
    port: 8080
    targetPort: 8080
  type: ClusterIP
