apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp-gwi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp-gwi
  template:
    metadata:
      labels:
        app: iotapp-gwi
    spec:
      containers:
      - name: iotapp-gwi-container
        image: iotapp-node-image:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          value: "gateway/gateway.js"
        - name: ARGS
          value: "--local_ip 0.0.0.0 --local_port 8181 --local_name gwi --remote_ip iotapp-server --remote_port 8080 --remote_name srv"
